#!/bin/bash

export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

sleep 1 # Delay needed to avoid DBUS introspection errors

node src/app.js --clear=true

while true; do
	sleep 100
done
